### ISSUE TITLE
360search: `m.so.com` is missing in urls

### ISSUE THREAD

**Issue by RussellLuo** [piwik/searchengine-and-social-list#36]
Possible update:

```
360search:
  - 
    urls:
      - so.360.cn
    params:
      - q
    backlink: 's?q={k}'
    charsets:
      - UTF-8
      - gb2312
  - 
    urls:
      - www.so.com
      - m.so.com  # added here
    params:
      - q
    backlink: 's?q={k}'
    charsets:
      - UTF-8
      - gb2312
```
